return function (connection, args)   
	connection:send("HTTP/1.0 200 OK\r\nContent-Type: application/json\r\nCache-Control: private, no-store\r\n\r\n")
	file.open("ACOn.txt", "r")
	connection:send(file.readline())
	connection:send("\n")
	file.close()
	file.open("Dim.txt", "r")
	connection:send(file.readline())
	connection:send("\n")
	file.close()
	file.open("LightName.txt", "r")
	connection:send(file.readline())
	connection:send("\n")
	file.close()
	file.open("PreviousLevel.txt", "r")
	connection:send(file.readline())
	connection:send("\n")
	file.close()
	file.open("Net.txt", "r")
	connection:send(file.readline())
	connection:send(file.readline())
	connection:send(file.readline())
	connection:send(file.readline())
	file.close()
end